spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authx_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*" # Not recommended in production
          auth: true
          starttls.enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 0n2f3j320c2n029j302jc09h2309cn232in02j9nc02c20n20nfknkhf920kjnsvna
      expiration: 86400000 # 24 hours

  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account

server:
  port: 8080